dnanexus-rnd/wdlTools

src/main/scala/wdlTools/cli/Format.scala
src/main/scala/wdlTools/cli/package.scala
src/main/scala/wdlTools/formatter/Upgrader.scala
src/main/scala/wdlTools/formatter/WdlV1Formatter.scala
src/main/scala/wdlTools/generators/ProjectGenerator.scala
src/main/scala/wdlTools/syntax/AbstractSyntax.scala
src/main/scala/wdlTools/syntax/Parsers.scala
src/main/scala/wdlTools/syntax/draft_2/ConcreteSyntax.scala
src/main/scala/wdlTools/syntax/draft_2/ParseAll.scala
src/main/scala/wdlTools/syntax/draft_2/ParseTop.scala
src/main/scala/wdlTools/syntax/draft_2/Translators.scala
src/main/scala/wdlTools/syntax/package.scala
src/main/scala/wdlTools/syntax/v1/ConcreteSyntax.scala
src/main/scala/wdlTools/syntax/v1/ParseAll.scala
src/main/scala/wdlTools/syntax/v1/ParseFragment.scala
src/main/scala/wdlTools/syntax/v1/ParseTop.scala
src/main/scala/wdlTools/syntax/v1/Translators.scala
src/main/scala/wdlTools/syntax/v1/package.scala
src/main/scala/wdlTools/typing/TypeChecker.scala
src/test/scala/wdlTools/format/BaseTest.scala
src/test/scala/wdlTools/syntax/AbstractSyntaxTest.scala
src/test/scala/wdlTools/syntax/draft_2/ConcreteSyntaxTest.scala
src/test/scala/wdlTools/syntax/v1/ConcreteSyntaxTest.scala
src/test/scala/wdlTools/typing/TypeCheckerTest.scala
src/test/scala/wdlTools/upgrade/BaseTest.scala

* AST changes:
* Add Version element
* Make doc optional in ImportDoc
* Make the various parts of Call be elements
* Unify WDL version naming (use v1/V1 everywhere)
* Remove followImports option from check command - type-checker always follows imports

AST changes, unify version naming (v1 rather than v1_0)

---

src/main/antlr4/draft_2/WdlDraft2Lexer.g4
src/main/antlr4/v1/WdlV1Lexer.g4
src/main/scala/wdlTools/cli/package.scala
src/main/scala/wdlTools/formatter/WdlV1Formatter.scala
src/main/scala/wdlTools/generators/ProjectGenerator.scala
src/main/scala/wdlTools/syntax/AbstractSyntax.scala
src/main/scala/wdlTools/syntax/Antlr4Util.scala
src/main/scala/wdlTools/syntax/draft_2/ConcreteSyntax.scala
src/main/scala/wdlTools/syntax/draft_2/ParseAll.scala
src/main/scala/wdlTools/syntax/draft_2/ParseTop.scala
src/main/scala/wdlTools/syntax/draft_2/Translators.scala
src/main/scala/wdlTools/syntax/package.scala
src/main/scala/wdlTools/syntax/v1/ConcreteSyntax.scala
src/main/scala/wdlTools/syntax/v1/ParseAll.scala
src/main/scala/wdlTools/syntax/v1/ParseTop.scala
src/main/scala/wdlTools/syntax/v1/Translators.scala
src/main/scala/wdlTools/typing/Stdlib.scala
src/main/scala/wdlTools/typing/TUtil.scala
src/main/scala/wdlTools/typing/TypeChecker.scala
src/main/scala/wdlTools/typing/package.scala
src/main/scala/wdlTools/util/Util.scala
src/main/scala/wdlTools/util/package.scala
src/test/scala/wdlTools/syntax/AbstractSyntaxTest.scala
src/test/scala/wdlTools/syntax/draft_2/ConcreteSyntaxTest.scala
src/test/scala/wdlTools/syntax/v1/ConcreteSyntaxTest.scala
src/test/scala/wdlTools/typing/TypeCheckerTest.scala

I am improving the formatter to handle in-line comments. Both this and the linter require more details about the location of elements in the source file. That is what (most of) these changes are supporting.
* Make ExprMap and ExprObject have element-type members rather than maps
* Make ImportDoc address an element (ImportAddr) rather than a URL: when the formatter re-writes the WDL it needs to know the address in the original file.
* Put docSourceURL in Document rather than TextSource: the URL is the same for all TextSources in a document, so it makes more sense to just put the URL at the top-level.
* Add endLine and endCol to TextSource
* Fix misnamed method getSourceText -> getTextSource
* Improve grammar to allow any whitespace between 'command' and '{'/'<<<'
* Few other cleanups

Some syntax changes to support development of linter and formatter

---

src/main/scala/wdlTools/cli/TypeCheck.scala
src/main/scala/wdlTools/linter/Linter.scala
src/main/scala/wdlTools/linter/Rules.scala
src/main/scala/wdlTools/types/Context.scala
src/main/scala/wdlTools/types/Stdlib.scala
src/main/scala/wdlTools/types/TypeInfer.scala
src/test/scala/wdlTools/eval/EvalTest.scala
src/test/scala/wdlTools/types/TypeInferTest.scala

The types Stdlib module handles handles variations in the standard library between WDL versions. Make it internal to type checking, so it isn't visible to the outside. This simplifies setting up and running the type-checker.

Handle WDL versions inside the types module

---

src/main/scala/wdlTools/eval/Eval.scala
src/main/scala/wdlTools/types/Stdlib.scala
src/main/scala/wdlTools/types/TypeInfer.scala
src/main/scala/wdlTools/types/TypedAbstractSyntax.scala
src/main/scala/wdlTools/types/Util.scala
src/main/scala/wdlTools/types/WdlTypes.scala

Add to the Typed Abstract Syntax the prototype of standard library functions at the call site.

Reporting prototypes for functions

---

src/main/scala/wdlTools/types/Context.scala
src/main/scala/wdlTools/types/TypeInfer.scala
src/main/scala/wdlTools/types/TypedAbstractSyntax.scala
src/main/scala/wdlTools/types/Util.scala
src/test/resources/wdlTools/types/v1/invalid_param_meta.wdl
src/test/scala/wdlTools/types/TypeInferTest.scala

* Add new elements to TST for WDL 2: None, Directory type, Call.afters, Hints
* Check parameter_meta keys against input and output declarations and throw exception if there is no match (this required adding an outputs Map to Context)
* Add to ImportAlias the T_Struct to which it refers
Note that this is just the second step in WDL 2.0 support (the first was adding the parser). There is still a third step of implementing type-checking and expression evaluation for these new types.

Additions to Type Syntax Tree and type inference

---

src/main/scala/wdlTools/eval/Eval.scala
src/main/scala/wdlTools/types/TypeInfer.scala
src/main/scala/wdlTools/types/TypedAbstractSyntax.scala

Made meta value naming more consistent in the typed abstract syntax.

Consistent naming for meta values

---

src/main/scala/wdlTools/types/TypeInfer.scala
src/main/scala/wdlTools/types/TypedAbstractSyntax.scala

Do we really need the `wdlType` field in Scatter? 
There is a lot of code now in dxWDL that relies on the Typed Abstract Syntax structures, so, I would rather not modify it if this isn't necessary. Also, the utility of this field is unclear to me.

wdlType field in Scatter

---

src/main/antlr4/v1/WdlV1Lexer.g4
src/main/antlr4/v1/WdlV1Parser.g4
src/main/antlr4/v2/WdlV2Lexer.g4
src/main/antlr4/v2/WdlV2Parser.g4
src/main/resources/templates/documentation/document.ssp
src/main/scala/wdlTools/formatter/WdlV1Formatter.scala
src/main/scala/wdlTools/formatter/package.scala
src/main/scala/wdlTools/generators/DocumentationGenerator.scala
src/main/scala/wdlTools/generators/ProjectGenerator.scala
src/main/scala/wdlTools/linter/LinterASTWalker.scala
src/main/scala/wdlTools/syntax/ASTWalker.scala
src/main/scala/wdlTools/syntax/AbstractSyntax.scala
src/main/scala/wdlTools/syntax/AllParseTreeListener.scala
src/main/scala/wdlTools/syntax/Util.scala
src/main/scala/wdlTools/syntax/draft_2/ParseAll.scala
src/main/scala/wdlTools/syntax/v1/ConcreteSyntax.scala
src/main/scala/wdlTools/syntax/v1/ParseAll.scala
src/main/scala/wdlTools/syntax/v1/ParseTop.scala
src/main/scala/wdlTools/syntax/v2/ConcreteSyntax.scala
src/main/scala/wdlTools/syntax/v2/ParseAll.scala
src/main/scala/wdlTools/syntax/v2/ParseTop.scala
src/main/scala/wdlTools/types/TypeInfer.scala
src/test/scala/wdlTools/syntax/AbstractSyntaxTest.scala
src/test/scala/wdlTools/syntax/v1/ConcreteSyntaxV1Test.scala

This PR implements separate handling of meta values from the grammar all the way through to AST. It also adds a 'null' keyword that is only recognized for meta values, so it is no longer necessary to handle null as a special-case identifier.

Use restricted value types for meta values

---

src/main/scala/wdlTools/types/Util.scala

A minor fix, putting double quotes around strings in the `exorToString` method.

Fixing double quotes

---

src/main/scala/wdlTools/eval/Stdlib.scala

Make the `read_string` stdlib function adhere to the specification. 
The read_string() function takes a file path which is expected to contain 1 line with 1 string on it. This function returns that string.

Correct implementation of read_string stdlib function

---

RELEASE_NOTES.md
src/main/resources/application.conf
src/main/scala/wdlTools/eval/Eval.scala
src/test/resources/eval/v1/empty_lines.wdl
src/test/resources/eval/v1/leading_spaces.wdl
src/test/resources/eval/v1/leading_spaces2.wdl
src/test/scala/wdlTools/eval/EvalTest.scala

Fixed bug when dealing with indentation.
Previously:
```
code
code
code
```
would turn into 
```
code
code
code
```
which would break some python code. Changed  so it reflects what was previously written in the function comments when dealing with whitespaces.
Note that empty line is going to be deleted only in case it does not contain any characters (including whitespace)

APPS-492:fixed indentation error

---

.github/workflows/main.yml
.github/workflows/release.yml
RELEASE_NOTES.md
src/main/antlr4/draft_2/WdlDraft2Lexer.g4
src/main/antlr4/draft_2/WdlDraft2Parser.g4
src/main/antlr4/v1/WdlV1Lexer.g4
src/main/antlr4/v1/WdlV1Parser.g4
src/main/antlr4/v1_1/WdlV1_1Lexer.g4
src/main/antlr4/v1_1/WdlV1_1Parser.g4
src/main/antlr4/v2/WdlV2Lexer.g4
src/main/antlr4/v2/WdlV2Parser.g4
src/main/scala/wdlTools/syntax/AllParseTreeListener.scala
src/main/scala/wdlTools/syntax/draft_2/ParseTop.scala
src/main/scala/wdlTools/syntax/v1/ParseAll.scala
src/main/scala/wdlTools/syntax/v1/ParseTop.scala
src/main/scala/wdlTools/syntax/v1_1/ParseTop.scala
src/main/scala/wdlTools/syntax/v2/ParseTop.scala
src/test/resources/eval/v1/simple_expr.wdl
src/test/resources/eval/v1/stdlib.wdl
src/test/scala/wdlTools/eval/EvalTest.scala

There were two issues:
* The grammar for string literals did not exactly match the spec with regards to escape sequences
* wdlTools was not translating escape sequence tokens into their literal values
This PR fixes both issues.

APPS-503 process escape sequences

---

.github/workflows/main.yml
RELEASE_NOTES.md
src/main/resources/application.conf
src/main/scala/wdlTools/eval/Eval.scala
src/test/resources/eval/v1/empty_lines.wdl
src/test/resources/eval/v1/leading_spaces.wdl
src/test/resources/eval/v1/leading_spaces2.wdl
src/test/scala/wdlTools/eval/EvalTest.scala

I merged the PR from @mhrvol fork into a new branch in the main repo.
@mhrvol: your change does fix the bug, but it also introduces a regression (unfortunately we did not have a test for it). The spec only states that common leading whitespace is removed, not blank lines (https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#stripping-leading-whitespace). The reason is illustrated by the following example:
```
./my-command ~{arg1} \
~{arg2}
./another-command
```
If `arg2` is an optional input with a null value, and empty lines are removed, then the evaluated script ends up as:
```
./my-command ~{arg1} \
./another-command
```
which causes an error. If, however, the empty line is preserved, everything works fine because an empty line ends the command.
I updated the code to preserve …

Apps 492 indentation

---

src/main/scala/wdlTools/generators/code/WdlFormatter.scala
src/main/scala/wdlTools/generators/code/WdlGenerator.scala
src/main/scala/wdlTools/generators/code/package.scala
src/main/scala/wdlTools/syntax/draft_2/ParseTop.scala
src/main/scala/wdlTools/syntax/v1/ParseTop.scala
src/main/scala/wdlTools/syntax/v1_1/ParseTop.scala
src/main/scala/wdlTools/syntax/v2/ParseTop.scala
src/test/resources/format/before/escape_sequences.wdl
src/test/scala/wdlTools/format/GeneratorTest.scala
src/test/scala/wdlTools/syntax/v1/ConcreteSyntaxV1Test.scala

Strings with escapes are parsed into multiple tokens. For example `"foo\\tbar"` would be parsed to `Vector(ExprString("foo"), ExprString("\"), ExprString("tbar"))`. One of the changes in this PR is to merge adjacent `ExprString`s to make escaping easier. The other change is to call `escape` on strings in the code formatter and generator, as long as they are not in the command section.

APPS-573 escape strings when generating/formatting code unless they are in the command block

---

RELEASE_NOTES.md
src/main/scala/wdlTools/generators/code/WdlFormatter.scala
src/main/scala/wdlTools/generators/code/WdlGenerator.scala
src/test/resources/syntax/v1_1/nested_expr.wdl
src/test/scala/wdlTools/syntax/v1_1/ConcreteSyntaxV1_1Test.scala

Expressions in placeholders are handled a bit differently, but this should only apply to the expression itself, not any expressions used in placeholder options.

Do not treat placeholder options as occurring 'inPlaceholder' when generating code

---

src/main/scala/wdlTools/generators/code/WdlFormatter.scala
src/main/scala/wdlTools/generators/code/WdlGenerator.scala
src/test/resources/format/before/sum_array.wdl
src/test/scala/wdlTools/format/GeneratorTest.scala

The previous fix for placeholders was not quite correct - it failed to put quotes around literal values. It also assumed you can't have nested placeholders, which is incorrect. This fixes both issues.

fix quoting of placeholder options

---

RELEASE_NOTES.md
src/main/scala/wdlTools/generators/code/WdlFormatter.scala
src/main/scala/wdlTools/generators/code/WdlGenerator.scala

A regression was introduced by #147. Expressions in placeholders are not meant to be line-wrapped. This PR again disables line wrapping in placeholders.

Disable line wrapping in placeholders

---

RELEASE_NOTES.md
build.sbt
doc/Commands/Fix.md
src/main/scala/wdlTools/cli/Fix.scala
src/main/scala/wdlTools/cli/Format.scala
src/main/scala/wdlTools/cli/Main.scala
src/main/scala/wdlTools/cli/Upgrade.scala
src/main/scala/wdlTools/cli/WdlToolsConf.scala
src/main/scala/wdlTools/cli/package.scala
src/main/scala/wdlTools/eval/Coercion.scala
src/main/scala/wdlTools/eval/Eval.scala
src/main/scala/wdlTools/generators/code/Upgrader.scala
src/main/scala/wdlTools/generators/code/WdlFormatter.scala
src/main/scala/wdlTools/generators/code/WdlGenerator.scala
src/main/scala/wdlTools/types/TypeInfer.scala
src/main/scala/wdlTools/types/Unification.scala

* Update dsScala to fix path relativization bugs
* Handle imports that are relative to a common ancestor of the importing file, but not in a subdirectory of the importing file's parent directory
* Make the file writing code into a common function shared by the `fix`, `format` and `upgrade` commands
* Allow return values of `read_*` functions to be immediately coerced to non-`String` values

Fix some issues with the `fix` command

---

RELEASE_NOTES.md
src/main/scala/wdlTools/types/Stdlib.scala
src/main/scala/wdlTools/types/TypeInfer.scala
src/test/resources/types/draft2/object_fields.wdl
src/test/scala/wdlTools/types/TypeInferComplianceTest.scala

An `Object` returned by the `read_object` function will have fields that are type `T_Any` but have `String` values. This PR allows expressions of type `T_Any` at type-check type type and the actual type will be checked at runtime.

Handle T_Any in placeholders

---

RELEASE_NOTES.md
src/main/scala/wdlTools/generators/code/WdlGenerator.scala
src/main/scala/wdlTools/syntax/package.scala
src/main/scala/wdlTools/types/TypeInfer.scala
src/test/resources/corpora_repos.json
src/test/resources/format/before/none_literal.wdl
src/test/scala/wdlTools/format/GeneratorTest.scala

In WDL 1.1+, optional inputs with a default value can be set to `None`, so the optional type needs to be maintained.

Don't unwrap optional for OverridableInputParameterWithDefault

---

RELEASE_NOTES.md
src/main/scala/wdlTools/eval/Runtime.scala

The `get` function coerces to the first allowed type. Since `Int` can be coerced to `String`, it returns a `String` even when the value is an `Int`. So `T_String` has to come last.

Return codes2
